parameters:
  deploy.deployments:
      spiegami:
        composer:
          path: '/var/bucket/nimbos.it/composer.phar'
          flags: ['prefer-dist', 'no-interaction', 'no-progress']
        path: '/var/bucket/nimbos.it/opensource/deeploy/example/deployments/spiegami.it'
        repository: 'git@bitbucket.org:nimbos/spiegami.it.git'

services:
  react.loop:
    factory: ["React\EventLoop\Factory", create]

  deploy.collection:
    class: "Deeploy\DeploymentCollection"
    arguments: [@react.loop, %deploy.deployments%]