parameters:
  deploy.deployments:
      deeploy:
        composer:
          path: './composer.phar'
          flags: ['prefer-dist', 'no-interaction', 'no-progress']
        path: './example/deployments/deeploy'
        repository: 'https://github.com/skedone/deeploy.git'

services:
  react.loop:
    factory: ["React\EventLoop\Factory", create]

  deploy.collection:
    class: "Deeploy\DeploymentCollection"
    arguments: [@react.loop, %deploy.deployments%]